apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sallyom-openshell
  labels:
    app.kubernetes.io/name: openshell
spec:
  to:
    kind: Service
    name: sallyom-openshell
  port:
    targetPort: 8080
  tls:
    termination: passthrough
